apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-scale-test

resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.5.5/install.yaml
- namespace.yaml
