apiVersion: v1
kind: Service
metadata:
  name: k8s-scale-test-service
  labels:
    app: k8s-scale-test
spec:
  type: ClusterIP
  selector:
    app: k8s-scale-test
  ports:
    - port: 8080
      targetPort: 8080
