apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
spec:
  project: default
  source:
    repoURL: https://github.com/honahuku/k8s-hands-on.git
    targetRevision: main
    path: manifest/apps/overlays/$(ENV)
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
