apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.9
    helm:
      releaseName: k8s-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
