apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- application.yaml
- argo-cd.yaml
# - argowf.yaml
- grafana.yaml
- k8s-monitoring.yaml
- k8s-scale-test.yaml
- metric-server.yaml
- namespace.yaml

configurations:
- kustomizeconfig.yaml

vars:
- fieldref:
    fieldPath: metadata.labels.env
  name: ENV
  objref:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    name: application
