apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
spec:
  project: default
  source:
    repoURL: https://github.com/honahuku/k8s-hands-on.git
    targetRevision: main
    path: manifest/metric-server/overlays/$(ENV)
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
